version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_password123"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  backend:
    build: ./backend/StudentFormApi
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__StudentFormConnection=Server=sqlserver,1433;Database=StudentFormDb;User Id=sa;Password=Your_password123;
    ports:
      - "5001:80"

  frontend:
    build: ./frontend/student-form-app
    ports:
      - "3000:80"
    depends_on:
      - backend

#  # Dacă dorești să adaugi Keycloak: error: Package 'Microsoft.AspNetCore.Authentication.JwtBearer' is incompatible with 'all' frameworks 
# in project 'C:\Users\Lenovo\OneDrive\Desktop\project\backend\StudentFormApi\StudentFormApi.csproj'.
#   keycloak:
#     image: quay.io/keycloak/keycloak:21.1.1
#     environment:
#       # Setează contul de admin
#       KEYCLOAK_ADMIN: admin
#       KEYCLOAK_ADMIN_PASSWORD: admin
#     command: start-dev
#     ports:
#       - "8080:8080"

volumes:
  sqlvolume:
